# Generated by Django 2.1.7 on 2019-06-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0024_auto_20190612_1744'),
        ('grants', '0024_auto_20190612_1645'),
    ]

    operations = [
    ]
